# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:
- bash: echo 'Hello World !" > testfile.txt 
  displayName: 'Create a file'

- task: GitHubRelease@0
  inputs:
    gitHubConnection: github-conn
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    #tag: # Required when action == Edit || Action == Delete || TagSource == Manual
    title: Test1
    releaseNotesSource: 'file'
    releaseNotesFile: testfile.txt
    #assets: '$(Build.ArtifactStagingDirectory)/*' # Optional
    #assetUploadMode: 'delete' # Optional. Options: delete, replace
    #isDraft: false # Optional
    #isPreRelease: false # Optional
    #addChangeLog: true # Optional
