pool:
  vmImage: 'macOS 10.13'

steps:

- script: |
    IMG_NAME='system-images;android-23;google_apis;x86'
    DEV_TYPE='Nexus 4'
    DEV_NAME="Nexus4Emu"
    $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-23;google_apis;x86"
    $ANDROID_HOME/tools/bin/avdmanager create avd --device "${DEV_TYPE}" --package "${IMG_NAME}" --abi google_apis/x86 --name "${DEV_NAME}"
    $ANDROID_HOME/emulator/emulator -avd Nexus4Emu &
    echo $! >> emu.pid
    sleep 60
    $ANDROID_HOME/platform-tools/adb devices
  displayName: 'Setup and Launch Emulator'

- script: |
    $ANDROID_HOME/platform-tools/adb devices
    $ANDROID_HOME/platform-tools/adb shell getprop sys.boot_completed
    $ANDROID_HOME/platform-tools/adb shell """
    mount -o rw,remount rootfs /;
    chmod 0777 /mnt/sdcard;
    exit
    """
    $ANDROID_HOME/platform-tools/adb shell mkdir -p /mnt/sdcard/DCIM/
    $ANDROID_HOME/platform-tools/adb shell """
        screenrecord /mnt/sdcard/DCIM/1.mp4;
        screenrecord /mnt/sdcard/DCIM/2.mp4;
        screenrecord /mnt/sdcard/DCIM/3.mp4;
        screenrecord /mnt/sdcard/DCIM/4.mp4;
        screenrecord /mnt/sdcard/DCIM/5.mp4;
        screenrecord /mnt/sdcard/DCIM/6.mp4;
        screenrecord /mnt/sdcard/DCIM/7.mp4;
        screenrecord /mnt/sdcard/DCIM/8.mp4;
        screenrecord /mnt/sdcard/DCIM/9.mp4;
        screenrecord /mnt/sdcard/DCIM/10.mp4; """ &
    echo $! > video.pid
    $ANDROID_HOME/platform-tools/adb logcat -c
    $ANDROID_HOME/platform-tools/adb logcat > $(Build.ArtifactStagingDirectory)/UIA-device.log &
    echo $! > logcat.pid
  displayName: 'Start Video Record and Logcat'

- script: |
    sleep 20
    kill -9 $(cat video.pid) || true
    sleep 10
    $ANDROID_HOME/platform-tools/adb pull /mnt/sdcard/DCIM/ $(Build.ArtifactStagingDirectory)/ || true
    kill -9 $(cat logcat.pid) || true
    adb kill-server
    kill -9 $(cat emu.pid)
  displayName: 'Copy Videos and Clean Up'

- task: PublishBuildArtifacts@1
  displayName: 'Publish'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: '$(Build.BuildId)'
    publishLocation: 'Container'
